export const RoomListings = [
  {
    id: 1,
    title: "Royal Suite, Executive lounge access, Suite, 1 King",
    roomtype: "Standard Room",
    bedtype: "Single / Twin",
    amenities: ["2 Double Beds", "Dinner", "Swimming Pool", "Wifi", "Free Parking", "TV", "Air Conditioning", "Balcony", "Smoking"],
    price: "$100.50",
    address: "1600 Northstar dr. Atlanta, GA 30012",
    description: "Welcome to our cozy Standard Room, ideal for solo travelers or couples. Enjoy modern amenities, including free Wi-Fi and a flat-screen TV. Relax in the queen-sized bed and refresh in the en-sui",
    maxOccupancy: {
      adults: 2,
      children: 1,
    },
    available: true,
    reservations: [],
  },
  {
    id: 2,
    title: "Royal Suite, Executive lounge access, Suite, 1 King",
    roomtype: "Deluxe Room",
    bedtype: "Double",
    amenities: ["2 Double Beds", "Dinner", "Swimming Pool", "Wifi", "Free Parking"],
    price: "$200.50",
    address: "1400 Northstar dr. Atlanta, FL 30012",
    description: "Welcome to our cozy Standard Room, ideal for solo travelers or couples.",
    maxOccupancy: {
      adults: 2,
      children: 1,
    },
    available: false,
    reservations: [
      { startDate: "2024-03-25", endDate: "2024-03-28" },
    ],
  },
  {
    id: 3,
    title: "Royal Suite, Executive lounge access, Suite, 1 King",
    roomtype: "Executive Room",
    bedtype: "King",
    amenities: ["Wifi", "Free Parking", "TV", "Air Conditioning", "Balcony", "Heating", "Bathtub", "Smoking"],

    price: "$300.50",
    address: "1600 Northstar dr. Atlanta, CA 30012",
    description: "Enjoy modern amenities, including free Wi-Fi and a flat-screen TV. Relax in the queen-sized bed and refresh in the en-sui",
    maxOccupancy: {
      adults: 2,
      children: 1,
    },
    available: false,
    reservations: [
      { startDate: "2024-03-25", endDate: "2024-03-28" },
    ],
  },
  {
    id: 4,
    title: "Royal Suite, Executive lounge access, Suite, 1 King",
    roomtype: "Superior Room",
    bedtype: "Queen",
    amenities: ["2 Double Beds", "Dinner", "Swimming Pool", "Wifi", "Free Parking", "TV", "Air Conditioning", "Balcony", "Heating", "Bathtub", "Smoking"],
    price: "$400.50",
    address: "1700 Northstar dr. Atlanta, GA 30012",
    description: "Welcome to our cozy Standard Room, ideal for solo travelers or couples. Enjoy modern amenities, including free Wi-Fi and a flat-screen TV.",
    maxOccupancy: {
      adults: 2,
      children: 1,
    },
    available: true,
    reservations: [
      { startDate: "2024-03-25", endDate: "2024-03-28" },
    ],
  },
  {
    id: 5,
    title: "Royal Suite, Executive lounge access, Suite, 1 King",
    roomtype: "Executive Room",
    bedtype: "Bunk Bed",
    amenities: ["2 Double Beds", "Dinner", "Swimming Pool", "Balcony", "Heating", "Bathtub", "Smoking"],
    price: "$500.50",
    address: "1600 Northstar dr. Atlanta, IL 30012",
    description: "Welcome to our cozy Standard Room, ideal for solo travelers or couples. Enjoy modern amenities, including free Wi-Fi and a flat-screen TV. Relax in the queen-sized bed and refresh in the en-sui",
    maxOccupancy: {
      adults: 2,
      children: 1,
    },
    available: true,
    reservations: [
      { startDate: "2024-03-25", endDate: "2024-03-28" },
    ],
  },
];